
package Artefacts;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ViewDocumentService", targetNamespace = "http://JaxWS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ViewDocumentService {


    /**
     * 
     * @param id
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "view", targetNamespace = "http://JaxWS/", className = "Artefacts.View")
    @ResponseWrapper(localName = "viewResponse", targetNamespace = "http://JaxWS/", className = "Artefacts.ViewResponse")
    @Action(input = "http://JaxWS/ViewDocumentService/viewRequest", output = "http://JaxWS/ViewDocumentService/viewResponse")
    public List<String> view(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

}
